version: '3'

services:
  build:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./grabscr:/build/grabscr
      - ./AppImageBuilder.yml:/build/AppImageBuilder.yml
      - ./appimage-dist:/build/appimage-dist
